#ifndef MENUSETTINGS_H
#define MENUSETTINGS_H
#define MENU_HEIGHT 30
#define FONT_FILENAME "ARCADECLASSIC.TTF"
#define FONT_SIZE 28
#define FONT_COLOR_R 254
#define FONT_COLOR_G 254
#define FONT_COLOR_B 102
#define BG_COLOR_R 1
#define BG_COLOR_G 205
#define BG_COLOR_B 254
#define MENU_DISTANCE 50
#endif // MENUSETTINGS_H
